apiVersion: v1
kind: Service
metadata:
  name: quickstart-kb-http-np
  namespace: default
  labels:
    common.k8s.elastic.co/type: kibana
    kibana.k8s.elastic.co/name: quickstart
spec:
  type: NodePort
  ports:
    - name: https
      port: 5601
      protocol: TCP
      targetPort: 5601
      nodePort: 32001
  selector:
    common.k8s.elastic.co/type: kibana
    kibana.k8s.elastic.co/name: quickstart