apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-12-15T08:29:27Z"
  labels:
    common.k8s.elastic.co/type: kibana
    kibana.k8s.elastic.co/name: quickstart
  name: quickstart-kb-http
  namespace: default
  ownerReferences:
  - apiVersion: kibana.k8s.elastic.co/v1
    blockOwnerDeletion: true
    controller: true
    kind: Kibana
    name: quickstart
    uid: 57c0ed41-5475-4c46-9aaf-434ee85ec6ac
  resourceVersion: "34500"
  uid: 630c57ad-56c9-4efc-a9c8-9d840cf6decf
spec:
  clusterIP: 10.96.68.97
  clusterIPs:
  - 10.96.68.97
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    common.k8s.elastic.co/type: kibana
    kibana.k8s.elastic.co/name: quickstart
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
